import '../styles/globals.css'
import styles from '../styles/Home.module.css'
import type { AppProps } from 'next/app'
import Image from 'next/image'
import Head from 'next/head'
import { Layout } from 'antd'

const { Header, Content, Footer, Sider } = Layout;

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <Layout>
      <Header>
        <Head>
          <title>Homebudget</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </Header>
      <Layout>
        <Sider>left sidebar</Sider>
        <Content>
          <main className={styles.main}>
            <Component {...pageProps} />
          </main>
        </Content>
      </Layout>
      <Footer>
        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' '}
            <span className={styles.logo}>
              <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
          </a>
        </footer>
      </Footer>
    </Layout>
  )
}

export default MyApp
